// <auto-generated />
using System;
using AndalusiaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AndalusiaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AndalusiaApp.Models.Application", b =>
                {
                    b.Property<long>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApplicationId"));

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<long?>("ProgramId")
                        .HasColumnType("bigint")
                        .HasColumnName("program_id");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("submission_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ApplicationId")
                        .HasName("pk_applications");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_applications_course_id");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("ix_applications_program_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_applications_schedule_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_applications_user_id");

                    b.ToTable("APPLICATIONS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Applications_CourseXorProgram", "([course_id] IS NOT NULL AND [program_id] IS NULL) OR ([course_id] IS NULL AND [program_id] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Applications_Status", "[status] IN ('Submitted','Under_Review','Approved','Rejected')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Assignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssignmentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int")
                        .HasColumnName("max_score");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("AssignmentId")
                        .HasName("pk_assignments");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_assignments_schedule_id");

                    b.ToTable("ASSIGNMENTS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.AssignmentSubmission", b =>
                {
                    b.Property<long>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("submission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubmissionId"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_number");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<long>("LearnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("learner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.HasKey("SubmissionId")
                        .HasName("pk_assignment_submissions");

                    b.HasIndex("LearnerId")
                        .HasDatabaseName("ix_assignment_submissions_learner_id");

                    b.HasIndex("AssignmentId", "LearnerId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_submissions_assignment_id_learner_id_attempt_number");

                    b.ToTable("ASSIGNMENT_SUBMISSIONS", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssignmentSubmissions_Status", "[status] IN ('Submitted','Late')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Attendance", b =>
                {
                    b.Property<long>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("attendance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttendanceId"));

                    b.Property<long>("LearnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("learner_id");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("marked_at");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("AttendanceId")
                        .HasName("pk_attendance");

                    b.HasIndex("LearnerId")
                        .HasDatabaseName("ix_attendance_learner_id");

                    b.HasIndex("SessionId", "LearnerId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_session_id_learner_id");

                    b.ToTable("ATTENDANCE", null, t =>
                        {
                            t.HasCheckConstraint("CK_Attendance_Status", "[status] IN ('Present','Absent','Late','Excused')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.CareerPath", b =>
                {
                    b.Property<long>("CareerPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("career_path_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CareerPathId"));

                    b.Property<string>("LearningJourney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("learning_journey");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("overview");

                    b.Property<string>("RecommendedSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recommended_skills");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("CareerPathId")
                        .HasName("pk_career_paths");

                    b.ToTable("CAREER_PATHS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit")
                        .HasColumnName("is_trending");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("slug");

                    b.HasKey("CategoryId")
                        .HasName("pk_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("CATEGORIES", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.ContactEnquiry", b =>
                {
                    b.Property<long>("EnquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("enquiry_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EnquiryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("subject_type");

                    b.HasKey("EnquiryId")
                        .HasName("pk_contact_enquiries");

                    b.ToTable("CONTACT_ENQUIRIES", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContactEnquiries_Status", "[status] IN ('New','In_Progress','Resolved','Closed')");

                            t.HasCheckConstraint("CK_ContactEnquiries_Subject", "[subject_type] IN ('General','Course','Program','Corporate')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.ContentPage", b =>
                {
                    b.Property<long>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("page_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PageId"));

                    b.Property<string>("ContentPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_payload");

                    b.Property<string>("PageKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("page_key");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("section_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.HasKey("PageId")
                        .HasName("pk_content_pages");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_content_pages_updated_by");

                    b.HasIndex("PageKey", "SectionKey")
                        .IsUnique()
                        .HasDatabaseName("ix_content_pages_page_key_section_key");

                    b.ToTable("CONTENT_PAGES", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CourseId"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("duration");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("objectives");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("CourseId")
                        .HasName("pk_courses");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_courses_category_id");

                    b.ToTable("COURSES", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courses_Status", "[status] IN ('Draft','Upcoming','Active','Closed')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.CourseMaterial", b =>
                {
                    b.Property<long>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("material_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaterialId"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("resource_type");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.HasKey("MaterialId")
                        .HasName("pk_course_materials");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_course_materials_course_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_course_materials_schedule_id");

                    b.ToTable("COURSE_MATERIALS", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourseMaterials_Type", "[resource_type] IN ('Slide','Document','Reference_Link')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.EmailVerificationToken", b =>
                {
                    b.Property<long>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("verification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VerificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("token");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("verified_at");

                    b.HasKey("VerificationId")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_email_verification_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_tokens_user_id");

                    b.ToTable("EMAIL_VERIFICATION_TOKENS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Enrollment", b =>
                {
                    b.Property<long>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EnrollmentId"));

                    b.Property<long?>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("enrolled_at");

                    b.Property<long?>("ProgramId")
                        .HasColumnType("bigint")
                        .HasColumnName("program_id");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("EnrollmentId")
                        .HasName("pk_enrollments");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollment_Application")
                        .HasFilter("[application_id] IS NOT NULL");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_enrollments_course_id");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("ix_enrollments_program_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_enrollments_schedule_id");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollment_Course")
                        .HasFilter("[course_id] IS NOT NULL AND [schedule_id] IS NULL");

                    b.HasIndex("UserId", "ProgramId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollment_Program")
                        .HasFilter("[program_id] IS NOT NULL AND [schedule_id] IS NULL");

                    b.HasIndex("UserId", "ScheduleId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollment_Schedule")
                        .HasFilter("[schedule_id] IS NOT NULL");

                    b.ToTable("ENROLLMENTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Enrollments_CourseXorProgram", "([course_id] IS NOT NULL AND [program_id] IS NULL) OR ([course_id] IS NULL AND [program_id] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Enrollments_Status", "[status] IN ('Enrolled','Active','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Faq", b =>
                {
                    b.Property<long>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("faq_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FaqId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("question");

                    b.HasKey("FaqId")
                        .HasName("pk_faqs");

                    b.HasIndex("OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("UX_Faq_General_Order")
                        .HasFilter("[category_id] IS NULL");

                    b.HasIndex("CategoryId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("UX_Faq_Category_Order")
                        .HasFilter("[category_id] IS NOT NULL");

                    b.ToTable("FAQS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Instructor", b =>
                {
                    b.Property<long>("InstructorId")
                        .HasColumnType("bigint")
                        .HasColumnName("instructor_id");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bio");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("job_title");

                    b.HasKey("InstructorId")
                        .HasName("pk_instructors");

                    b.ToTable("INSTRUCTORS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.InstructorPayout", b =>
                {
                    b.Property<long>("PayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payout_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PayoutId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<long>("InstructorId")
                        .HasColumnType("bigint")
                        .HasColumnName("instructor_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<long>("ProcessedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("processed_by");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("PayoutId")
                        .HasName("pk_instructor_payouts");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("ix_instructor_payouts_instructor_id");

                    b.HasIndex("ProcessedBy")
                        .HasDatabaseName("ix_instructor_payouts_processed_by");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_instructor_payouts_schedule_id");

                    b.ToTable("INSTRUCTOR_PAYOUTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_InstructorPayouts_Status", "[status] IN ('Pending','Paid','Cancelled')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("NOTIFICATIONS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Partner", b =>
                {
                    b.Property<long>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("partner_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PartnerId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("PartnerId")
                        .HasName("pk_partners");

                    b.ToTable("PARTNERS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Partners_Type", "[type] IN ('Accreditation','Success_Partner')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.PasswordResetToken", b =>
                {
                    b.Property<long>("ResetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reset_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResetId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ResetId")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("PASSWORD_RESET_TOKENS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<long?>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<long?>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gateway_name");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transaction_ref");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId")
                        .HasName("pk_payments");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_payments_application_id");

                    b.HasIndex("EnrollmentId")
                        .HasDatabaseName("ix_payments_enrollment_id");

                    b.HasIndex("TransactionRef")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_transaction_ref");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payments_user_id");

                    b.ToTable("PAYMENTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Status", "[status] IN ('Initiated','Success','Failed','Refunded')");

                            t.HasCheckConstraint("CK_Payments_Target", "[application_id] IS NOT NULL OR [enrollment_id] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.HasKey("PermissionId")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.ToTable("PERMISSIONS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Program", b =>
                {
                    b.Property<long>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("program_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProgramId"));

                    b.Property<long?>("CareerPathId")
                        .HasColumnType("bigint")
                        .HasColumnName("career_path_id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("duration");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("overview");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("structure");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("ProgramId")
                        .HasName("pk_programs");

                    b.HasIndex("CareerPathId")
                        .HasDatabaseName("ix_programs_career_path_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_programs_category_id");

                    b.ToTable("PROGRAMS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Programs_Status", "[status] IN ('Draft','Active','Archived')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.ProgramCourse", b =>
                {
                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint")
                        .HasColumnName("program_id");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.HasKey("ProgramId", "CourseId")
                        .HasName("pk_program_courses");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_program_courses_course_id");

                    b.ToTable("PROGRAM_COURSES", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Progress", b =>
                {
                    b.Property<long>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("progress_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProgressId"));

                    b.Property<int>("CompletedSessionsCount")
                        .HasColumnType("int")
                        .HasColumnName("completed_sessions_count");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated_at");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("progress_percentage");

                    b.Property<int>("SubmittedAssignmentsCount")
                        .HasColumnType("int")
                        .HasColumnName("submitted_assignments_count");

                    b.HasKey("ProgressId")
                        .HasName("pk_progress");

                    b.HasIndex("EnrollmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_progress_enrollment_id");

                    b.ToTable("PROGRESS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.RelatedCourse", b =>
                {
                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<long>("RelatedCourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("related_course_id");

                    b.HasKey("CourseId", "RelatedCourseId")
                        .HasName("pk_related_courses");

                    b.HasIndex("RelatedCourseId")
                        .HasDatabaseName("ix_related_courses_related_course_id");

                    b.ToTable("RELATED_COURSES", null, t =>
                        {
                            t.HasCheckConstraint("CK_RelatedCourses_NotSelf", "[course_id] <> [related_course_id]");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.RelatedProgram", b =>
                {
                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint")
                        .HasColumnName("program_id");

                    b.Property<long>("RelatedProgramId")
                        .HasColumnType("bigint")
                        .HasColumnName("related_program_id");

                    b.HasKey("ProgramId", "RelatedProgramId")
                        .HasName("pk_related_programs");

                    b.HasIndex("RelatedProgramId")
                        .HasDatabaseName("ix_related_programs_related_program_id");

                    b.ToTable("RELATED_PROGRAMS", null, t =>
                        {
                            t.HasCheckConstraint("CK_RelatedPrograms_NotSelf", "[program_id] <> [related_program_id]");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("RoleId")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("ROLES", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Learner"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Instructor"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "Content_Manager"
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("ROLE_PERMISSIONS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Schedule", b =>
                {
                    b.Property<long>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScheduleId"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("batch_code");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<long?>("ProgramId")
                        .HasColumnType("bigint")
                        .HasColumnName("program_id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_number");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("venue_name");

                    b.HasKey("ScheduleId")
                        .HasName("pk_schedules");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_schedules_course_id");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("ix_schedules_program_id");

                    b.ToTable("SCHEDULES", null, t =>
                        {
                            t.HasCheckConstraint("CK_Schedules_CourseXorProgram", "([course_id] IS NOT NULL AND [program_id] IS NULL) OR ([course_id] IS NULL AND [program_id] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Schedules_Status", "[status] IN ('Scheduled','Running','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.ScheduleInstructor", b =>
                {
                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<long>("InstructorId")
                        .HasColumnType("bigint")
                        .HasColumnName("instructor_id");

                    b.HasKey("ScheduleId", "InstructorId")
                        .HasName("pk_schedule_instructors");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("ix_schedule_instructors_instructor_id");

                    b.ToTable("SCHEDULE_INSTRUCTORS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Session", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<string>("RoomDetails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("room_details");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("SessionId")
                        .HasName("pk_sessions");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_sessions_schedule_id");

                    b.ToTable("SESSIONS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Testimonial", b =>
                {
                    b.Property<long>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("testimonial_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TestimonialId"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("client_name");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("is_featured");

                    b.Property<string>("QuoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("quote_text");

                    b.Property<string>("TitleOrRole")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title_or_role");

                    b.HasKey("TestimonialId")
                        .HasName("pk_testimonials");

                    b.ToTable("TESTIMONIALS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("preferred_language");

                    b.Property<DateTime>("TermsAcceptedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("terms_accepted_at");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("USER_ROLES", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Application", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_applications_courses_course_id");

                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_applications_programs_program_id");

                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_applications_schedules_schedule_id");

                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_applications_users_user_id");

                    b.Navigation("Course");

                    b.Navigation("Program");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Assignment", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AndalusiaApp.Models.AssignmentSubmission", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_submissions_assignments_assignment_id");

                    b.HasOne("AndalusiaApp.Models.User", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_submissions_users_learner_id");

                    b.Navigation("Assignment");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Attendance", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_users_learner_id");

                    b.HasOne("AndalusiaApp.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_sessions_session_id");

                    b.Navigation("Learner");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AndalusiaApp.Models.ContentPage", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_pages_users_updated_by");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Course", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courses_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AndalusiaApp.Models.CourseMaterial", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_materials_courses_course_id");

                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_course_materials_schedules_schedule_id");

                    b.Navigation("Course");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AndalusiaApp.Models.EmailVerificationToken", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Enrollment", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_enrollments_applications_application_id");

                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_enrollments_courses_course_id");

                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_enrollments_programs_program_id");

                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_enrollments_schedules_schedule_id");

                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_users_user_id");

                    b.Navigation("Application");

                    b.Navigation("Course");

                    b.Navigation("Program");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Faq", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Category", "Category")
                        .WithMany("Faqs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_faqs_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Instructor", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithOne("Instructor")
                        .HasForeignKey("AndalusiaApp.Models.Instructor", "InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instructors_users_instructor_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.InstructorPayout", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Instructor", "Instructor")
                        .WithMany("Payouts")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instructor_payouts_instructors_instructor_id");

                    b.HasOne("AndalusiaApp.Models.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instructor_payouts_users_processed_by");

                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_instructor_payouts_schedules_schedule_id");

                    b.Navigation("Instructor");

                    b.Navigation("ProcessedByUser");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Notification", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.PasswordResetToken", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Payment", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_applications_application_id");

                    b.HasOne("AndalusiaApp.Models.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_enrollments_enrollment_id");

                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_user_id");

                    b.Navigation("Application");

                    b.Navigation("Enrollment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Program", b =>
                {
                    b.HasOne("AndalusiaApp.Models.CareerPath", "CareerPath")
                        .WithMany("Programs")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_programs_career_paths_career_path_id");

                    b.HasOne("AndalusiaApp.Models.Category", "Category")
                        .WithMany("Programs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_programs_categories_category_id");

                    b.Navigation("CareerPath");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AndalusiaApp.Models.ProgramCourse", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany("ProgramCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_program_courses_courses_course_id");

                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany("ProgramCourses")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_courses_programs_program_id");

                    b.Navigation("Course");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Progress", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Enrollment", "Enrollment")
                        .WithOne("Progress")
                        .HasForeignKey("AndalusiaApp.Models.Progress", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_progress_enrollments_enrollment_id");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("AndalusiaApp.Models.RelatedCourse", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_related_courses_courses_course_id");

                    b.HasOne("AndalusiaApp.Models.Course", "Related")
                        .WithMany()
                        .HasForeignKey("RelatedCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_related_courses_courses_related_course_id");

                    b.Navigation("Course");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("AndalusiaApp.Models.RelatedProgram", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_related_programs_programs_program_id");

                    b.HasOne("AndalusiaApp.Models.Program", "Related")
                        .WithMany()
                        .HasForeignKey("RelatedProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_related_programs_programs_related_program_id");

                    b.Navigation("Program");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("AndalusiaApp.Models.RolePermission", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("AndalusiaApp.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Schedule", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_schedules_courses_course_id");

                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_schedules_programs_program_id");

                    b.Navigation("Course");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("AndalusiaApp.Models.ScheduleInstructor", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Instructor", "Instructor")
                        .WithMany("ScheduleInstructors")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_instructors_instructors_instructor_id");

                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany("ScheduleInstructors")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_instructors_schedules_schedule_id");

                    b.Navigation("Instructor");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Session", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany("Sessions")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AndalusiaApp.Models.UserRole", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.CareerPath", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Category", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Faqs");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Course", b =>
                {
                    b.Navigation("ProgramCourses");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Enrollment", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Instructor", b =>
                {
                    b.Navigation("Payouts");

                    b.Navigation("ScheduleInstructors");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Program", b =>
                {
                    b.Navigation("ProgramCourses");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Schedule", b =>
                {
                    b.Navigation("ScheduleInstructors");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AndalusiaApp.Models.User", b =>
                {
                    b.Navigation("Instructor");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
