// <auto-generated />
using System;
using AndalusiaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Andalusia.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003192917_ArchAndEdits")]
    partial class ArchAndEdits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AndalusiaApp.Models.Application", b =>
                {
                    b.Property<long>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApplicationId"));

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("APPLICATIONS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Applications_CourseXorProgram", "([CourseId] IS NOT NULL AND [ProgramId] IS NULL) OR ([CourseId] IS NULL AND [ProgramId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Applications_Status", "[Status] IN ('Submitted','Under_Review','Approved','Rejected')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Assignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssignmentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ASSIGNMENTS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.AssignmentSubmission", b =>
                {
                    b.Property<long>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubmissionId"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("LearnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubmissionId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("AssignmentId", "LearnerId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("ASSIGNMENT_SUBMISSIONS", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssignmentSubmissions_Status", "[Status] IN ('Submitted','Late')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Attendance", b =>
                {
                    b.Property<long>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttendanceId"));

                    b.Property<long>("LearnerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("SessionId", "LearnerId")
                        .IsUnique();

                    b.ToTable("ATTENDANCE", null, t =>
                        {
                            t.HasCheckConstraint("CK_Attendance_Status", "[Status] IN ('Present','Absent','Late','Excused')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.CareerPath", b =>
                {
                    b.Property<long>("CareerPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CareerPathId"));

                    b.Property<string>("LearningJourney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendedSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CareerPathId");

                    b.ToTable("CAREER_PATHS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("CATEGORIES", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.ContactEnquiry", b =>
                {
                    b.Property<long>("EnquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EnquiryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("HandledBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("EnquiryId");

                    b.HasIndex("HandledBy");

                    b.HasIndex("UserId");

                    b.ToTable("CONTACT_ENQUIRIES", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContactEnquiries_Status", "[Status] IN ('New','In_Progress','Resolved','Closed')");

                            t.HasCheckConstraint("CK_ContactEnquiries_Subject", "[SubjectType] IN ('General','Course','Program','Corporate')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.ContentPage", b =>
                {
                    b.Property<long>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PageId"));

                    b.Property<string>("ContentPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("PageId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("PageKey", "SectionKey")
                        .IsUnique();

                    b.ToTable("CONTENT_PAGES", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CourseId"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("COURSES", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courses_Status", "[Status] IN ('Draft','Upcoming','Active','Closed')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.CourseMaterial", b =>
                {
                    b.Property<long>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaterialId"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MaterialId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("COURSE_MATERIALS", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourseMaterials_Type", "[ResourceType] IN ('Slide','Document','Reference_Link')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.EmailVerificationToken", b =>
                {
                    b.Property<long>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VerificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VerificationId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EMAIL_VERIFICATION_TOKENS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Enrollment", b =>
                {
                    b.Property<long>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EnrollmentId"));

                    b.Property<long?>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollment_Application")
                        .HasFilter("[ApplicationId] IS NOT NULL");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollment_Course")
                        .HasFilter("[CourseId] IS NOT NULL AND [ScheduleId] IS NULL");

                    b.HasIndex("UserId", "ProgramId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollment_Program")
                        .HasFilter("[ProgramId] IS NOT NULL AND [ScheduleId] IS NULL");

                    b.HasIndex("UserId", "ScheduleId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollment_Schedule")
                        .HasFilter("[ScheduleId] IS NOT NULL");

                    b.ToTable("ENROLLMENTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Enrollments_CourseXorProgram", "([CourseId] IS NOT NULL AND [ProgramId] IS NULL) OR ([CourseId] IS NULL AND [ProgramId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Enrollments_Status", "[Status] IN ('Enrolled','Active','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Faq", b =>
                {
                    b.Property<long>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FaqId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("FaqId");

                    b.HasIndex("OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("UX_Faq_General_Order")
                        .HasFilter("[CategoryId] IS NULL");

                    b.HasIndex("CategoryId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("UX_Faq_Category_Order")
                        .HasFilter("[CategoryId] IS NOT NULL");

                    b.ToTable("FAQS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Instructor", b =>
                {
                    b.Property<long>("InstructorId")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstructorId");

                    b.ToTable("INSTRUCTORS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.InstructorPayout", b =>
                {
                    b.Property<long>("PayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PayoutId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("InstructorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProcessedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PayoutId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("ScheduleId");

                    b.ToTable("INSTRUCTOR_PAYOUTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_InstructorPayouts_Status", "[Status] IN ('Pending','Paid','Cancelled')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("NOTIFICATIONS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Partner", b =>
                {
                    b.Property<long>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PartnerId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PartnerId");

                    b.ToTable("PARTNERS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Partners_Type", "[Type] IN ('Accreditation','Success_Partner')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.PasswordResetToken", b =>
                {
                    b.Property<long>("ResetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResetId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ResetId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PASSWORD_RESET_TOKENS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("EnrollmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PaymentId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("TransactionRef")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PAYMENTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Status", "[Status] IN ('Initiated','Success','Failed','Refunded')");

                            t.HasCheckConstraint("CK_Payments_Target", "[ApplicationId] IS NOT NULL OR [EnrollmentId] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PermissionId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PERMISSIONS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Program", b =>
                {
                    b.Property<long>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProgramId"));

                    b.Property<long?>("CareerPathId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProgramId");

                    b.HasIndex("CareerPathId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PROGRAMS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Programs_Status", "[status] IN ('Draft','Active','Archived')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.ProgramCourse", b =>
                {
                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("ProgramId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("PROGRAM_COURSES", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.ProgramPartner", b =>
                {
                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("PartnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("AccreditationDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ProgramId", "PartnerId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PROGRAM_PARTNERS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Progress", b =>
                {
                    b.Property<long>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProgressId"));

                    b.Property<int>("CompletedSessionsCount")
                        .HasColumnType("int");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SubmittedAssignmentsCount")
                        .HasColumnType("int");

                    b.HasKey("ProgressId");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("PROGRESS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.RelatedCourse", b =>
                {
                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("RelatedCourseId")
                        .HasColumnType("bigint");

                    b.HasKey("CourseId", "RelatedCourseId");

                    b.HasIndex("RelatedCourseId");

                    b.ToTable("RELATED_COURSES", null, t =>
                        {
                            t.HasCheckConstraint("CK_RelatedCourses_NotSelf", "[CourseId] <> [RelatedCourseId]");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.RelatedProgram", b =>
                {
                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("RelatedProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("ProgramId", "RelatedProgramId");

                    b.HasIndex("RelatedProgramId");

                    b.ToTable("RELATED_PROGRAMS", null, t =>
                        {
                            t.HasCheckConstraint("CK_RelatedPrograms_NotSelf", "[ProgramId] <> [RelatedProgramId]");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ROLES", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Learner"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Instructor"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "Content_Manager"
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ROLE_PERMISSIONS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Schedule", b =>
                {
                    b.Property<long>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScheduleId"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<long?>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProgramId");

                    b.ToTable("SCHEDULES", null, t =>
                        {
                            t.HasCheckConstraint("CK_Schedules_CourseXorProgram", "([CourseId] IS NOT NULL AND [ProgramId] IS NULL) OR ([CourseId] IS NULL AND [ProgramId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Schedules_Status", "[Status] IN ('Scheduled','Running','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("AndalusiaApp.Models.ScheduleInstructor", b =>
                {
                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<long>("InstructorId")
                        .HasColumnType("bigint");

                    b.HasKey("ScheduleId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("SCHEDULE_INSTRUCTORS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Session", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("RoomDetails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SessionId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("SESSIONS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Testimonial", b =>
                {
                    b.Property<long>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TestimonialId"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("QuoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleOrRole")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("TestimonialId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("TESTIMONIALS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("TermsAcceptedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("USER_ROLES", (string)null);
                });

            modelBuilder.Entity("AndalusiaApp.Models.Application", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Program");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Assignment", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AndalusiaApp.Models.AssignmentSubmission", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.User", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Attendance", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AndalusiaApp.Models.ContactEnquiry", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "HandledByUser")
                        .WithMany("HandledEnquiries")
                        .HasForeignKey("HandledBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany("SubmittedEnquiries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HandledByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.ContentPage", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Course", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AndalusiaApp.Models.CourseMaterial", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AndalusiaApp.Models.EmailVerificationToken", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Enrollment", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Course");

                    b.Navigation("Program");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Faq", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Category", "Category")
                        .WithMany("Faqs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Instructor", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithOne("Instructor")
                        .HasForeignKey("AndalusiaApp.Models.Instructor", "InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.InstructorPayout", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Instructor", "Instructor")
                        .WithMany("Payouts")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instructor");

                    b.Navigation("ProcessedByUser");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Notification", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.PasswordResetToken", b =>
                {
                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Payment", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Enrollment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Program", b =>
                {
                    b.HasOne("AndalusiaApp.Models.CareerPath", "CareerPath")
                        .WithMany("Programs")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.Category", "Category")
                        .WithMany("Programs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CareerPath");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AndalusiaApp.Models.ProgramCourse", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany("ProgramCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany("ProgramCourses")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("AndalusiaApp.Models.ProgramPartner", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Partner", "Partner")
                        .WithMany("ProgramPartners")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany("ProgramPartners")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Progress", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Enrollment", "Enrollment")
                        .WithOne("Progress")
                        .HasForeignKey("AndalusiaApp.Models.Progress", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("AndalusiaApp.Models.RelatedCourse", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.Course", "Related")
                        .WithMany()
                        .HasForeignKey("RelatedCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("AndalusiaApp.Models.RelatedProgram", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.Program", "Related")
                        .WithMany()
                        .HasForeignKey("RelatedProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("AndalusiaApp.Models.RolePermission", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Schedule", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("AndalusiaApp.Models.ScheduleInstructor", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Instructor", "Instructor")
                        .WithMany("ScheduleInstructors")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany("ScheduleInstructors")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Session", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Schedule", "Schedule")
                        .WithMany("Sessions")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Testimonial", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Course", "Course")
                        .WithMany("Testimonials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany("Testimonials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.UserRole", b =>
                {
                    b.HasOne("AndalusiaApp.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AndalusiaApp.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndalusiaApp.Models.CareerPath", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Category", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Faqs");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Course", b =>
                {
                    b.Navigation("ProgramCourses");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Enrollment", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Instructor", b =>
                {
                    b.Navigation("Payouts");

                    b.Navigation("ScheduleInstructors");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Partner", b =>
                {
                    b.Navigation("ProgramPartners");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Program", b =>
                {
                    b.Navigation("ProgramCourses");

                    b.Navigation("ProgramPartners");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AndalusiaApp.Models.Schedule", b =>
                {
                    b.Navigation("ScheduleInstructors");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AndalusiaApp.Models.User", b =>
                {
                    b.Navigation("HandledEnquiries");

                    b.Navigation("Instructor");

                    b.Navigation("SubmittedEnquiries");

                    b.Navigation("Testimonials");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
