<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Andalusia.Domain\Andalusia.Domain.csproj" />
    <ProjectReference Include="..\Andalusia.ServicesAbstraction\Andalusia.ServicesAbstraction.csproj" />
  </ItemGroup>

</Project>
